# Generated by Django 5.2.9 on 2025-12-12 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nacionalidad', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICO', 'Jurídico')], max_length=20)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='bancos.banco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
