# Generated by Django 5.2.9 on 2025-12-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default=12345678, help_text='Documento Nacional de Identidad', max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
